export enum CATEGORY_OPTION {
  ALL = "ALL",
  GAME_DEVELOPMENT = "GAME_DEVELOPMENT",
  WEB_DEVELOPMENT = "WEB_DEVELOPMENT",
  AI = "AI",
  VLOG = "VLOG",
}

export enum PRICE_OPTION {
  FREE = "FREE",
  PAID = "PAID",
}

export enum RESOLVE_OPTION {
  RESOLVED = "RESOLVED",
  UNRESOLVED = "UNRESOLVED",
}

export enum SORT_OPTION {
  MOST_POPULAR = "MOST_POPULAR",
  HIGHEST_RATE = "HIGHEST_RATE",
  NEWEST = "NEWEST",
}
