export * from "./NavigationLayout";
export { default as NavigationLayout } from "./NavigationLayout";
export { default as RestrictLayout } from "./RestrictLayout";
export { default as BannerLayout } from "./BannerLayout";
export { default as FilterLayout } from "./FilterLayout";
export { default as CourseLayout } from "./CourseLayout";
export { default as DualColorLayout } from "./DualColorLayout";
export { default as LessonLayout } from "./LessonLayout";
export { default as QuestionLayout } from "../organisms/Question/QuestionLayout";
export { default as ProfileLayout } from "./ProfileLayout";
export { default as InstructorDashboardLayout } from "./InstructorDashboardLayout";
