export enum REACT_QUERY_ACTION_KEYS {
  GET = "GET",
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
}

export enum REACT_QUERY_FILTER_KEYS {
  GET_TOP = "GET_TOP",
  GET_LATEST = "GET_LATEST",
  GET_LIST = "GET_LIST",
  GET_DETAIL = "GET_DETAIL",
}
